### ISSUE TITLE
Система сборки

### ISSUE THREAD

**Issue by gltronred** [AlexandrTerentyev/Quantum#2]
Как системный администратор, я бы хотел иметь возможность запустить скрипт генерации jar-файла библиотек и демонстрационных программ, с указанными зависимостями и т.п. 

Насколько я понимаю, это можно каким-то образом вытащить из проекта в IDEA. Пожалуйста, сделайте это и выложите скрипт для maven/gradle/whatever в репозиторий.

**Comment by AlexandrTerentyev** [comment]
я добавил ссылку для скачивания актуальной версии jar файла

**Comment by gltronred** [comment]
Хотелось бы всё же, чтобы был скрипт для сборки. Всё же jar-файл можно забыть выложить, зависимости могут обновиться и т.п.
